CREATE TABLE ATTACHMENT ( ID NUMBER(19) NOT NULL, FILE_NAME VARCHAR2(100), FILE_PATH VARCHAR2(1000), TYPE NUMBER(5), TYPE_ID NUMBER(19), PRIMARY KEY (ID) );
CREATE TABLE AUTHORITY ( ID NUMBER(19) NOT NULL, DATA_URL VARCHAR2(100) NOT NULL, MENU_CLASS VARCHAR2(50) NOT NULL, MENU_CODE VARCHAR2(50) NOT NULL, MENU_NAME VARCHAR2(50) NOT NULL, PARENT_MENUCODE VARCHAR2(50), SEQUENCE NUMBER(19), PRIMARY KEY (ID), CONSTRAINT UK_81U1T17MR18PWIAP87MBP7PGR UNIQUE (MENU_CODE) );
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (1, '#', 'menu-icon fa fa-desktop', 'systemmanagement', '系统管理', '0', 1);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (2, 'page/sysuser', 'menu-icon fa fa-caret-right', 'sysuser', '用户管理', 'systemmanagement', 1);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (3, 'page/department', 'menu-icon fa fa-caret-right', 'department', '部门管理', 'systemmanagement', 2);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (4, 'page/dict', 'menu-icon fa fa-caret-right', 'dict', '字典管理', 'systemmanagement', 3);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (5, 'page/role', 'menu-icon fa fa-caret-right', 'role', '角色权限管理', 'systemmanagement', 4);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (6, 'page/authority', 'menu-icon fa fa-caret-right', 'authority', '菜单管理', 'systemmanagement', 5);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (7, 'page/mail', 'menu-icon fa fa-caret-right', 'mail', '邮件收发管理', 'systemmanagement', 6);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (8, '#', 'menu-icon fa fa-list', 'informationmanagement', '信息管理', '0', 2);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (9, 'page/information', 'menu-icon fa fa-caret-right', 'information', '信息发布管理', 'informationmanagement', 1);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (10, '#', 'menu-icon fa fa-pencil-square-o', 'bootstrapinstance', 'Bootstrap常用实例', '0', 4);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (11, 'page/typography', 'menu-icon fa fa-caret-right', 'typography', '排版', 'bootstrapinstance', 1);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (12, 'page/uielements', 'menu-icon fa fa-caret-right', 'uielements', 'UI元素', 'bootstrapinstance', 2);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (13, 'page/buttonsicon', 'menu-icon fa fa-caret-right', 'buttonsicon', '按钮图标', 'bootstrapinstance', 3);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (14, 'page/contentslider', 'menu-icon fa fa-caret-right', 'contentslider', '侧边栏滑块', 'bootstrapinstance', 4);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (15, 'page/nestablelist', 'menu-icon fa fa-caret-right', 'nestablelist', '嵌套拖拽列表', 'bootstrapinstance', 5);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (16, 'page/jquerydatatables', 'menu-icon fa fa-caret-right', 'jquerydatatables', 'jQuery DataTables', 'bootstrapinstance', 6);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (17, 'page/formelements', 'menu-icon fa fa-caret-right', 'formelements', '表单元素', 'bootstrapinstance', 7);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (18, 'page/formelements2', 'menu-icon fa fa-caret-right', 'formelements2', '表单元素2', 'bootstrapinstance', 8);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (19, 'page/wizardvalidation', 'menu-icon fa fa-caret-right', 'wizardvalidation', '向导验证', 'bootstrapinstance', 9);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (20, 'page/uiwidgets', 'menu-icon fa fa-caret-right', 'uiwidgets', 'UI组件', 'bootstrapinstance', 10);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (21, 'page/calendar', 'menu-icon fa fa-caret-right', 'calendar', ' 日历记事', 'bootstrapinstance', 11);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (22, 'page/gallery', 'menu-icon fa fa-caret-right', 'gallery', '相册', 'bootstrapinstance', 12);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (23, 'page/pricingtables', 'menu-icon fa fa-caret-right', 'pricingtables', '价格表格', 'bootstrapinstance', 13);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (24, 'page/invoice', 'menu-icon fa fa-caret-right', 'invoice', '发票', 'bootstrapinstance', 14);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (25, 'page/timeline', 'menu-icon fa fa-caret-right', 'timeline', '时间轴', 'bootstrapinstance', 15);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (26, 'page/faq', 'menu-icon fa fa-caret-right', 'faq', '问答帮助', 'bootstrapinstance', 16);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (27, 'page/error404', 'menu-icon fa fa-caret-right', 'error404', '404页面', 'bootstrapinstance', 17);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (28, 'page/error500', 'menu-icon fa fa-caret-right', 'error500', '500页面', 'bootstrapinstance', 18);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (29, 'page/grid', 'menu-icon fa fa-caret-right', 'grid', 'Bootstrap Grid', 'bootstrapinstance', 19);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (30, '#', 'menu-icon fa fa-bar-chart', 'chartsreports', '图表/报表', '0', 3);
insert into AUTHORITY (ID, DATA_URL, MENU_CLASS, MENU_CODE, MENU_NAME, PARENT_MENUCODE, SEQUENCE) values (31, 'page/charts', 'menu-icon fa fa-caret-right', 'charts', '图表', 'chartsreports', 1);
CREATE TABLE DEPARTMENT ( ID NUMBER(19) NOT NULL, DEPARTMENT_KEY VARCHAR2(20) NOT NULL, DEPARTMENT_VALUE VARCHAR2(40) NOT NULL, DESCRIPTION VARCHAR2(200), PARENT_DEPARTMENTKEY VARCHAR2(20), PRIMARY KEY (ID), CONSTRAINT UK_A2K9GINQLRA87VJOAC9JOTIED UNIQUE (DEPARTMENT_KEY) );
insert into DEPARTMENT (ID, DEPARTMENT_KEY, DEPARTMENT_VALUE, DESCRIPTION, PARENT_DEPARTMENTKEY) values (1, 'YFB', '研发部', '研发部是核心的部门', null);
insert into DEPARTMENT (ID, DEPARTMENT_KEY, DEPARTMENT_VALUE, DESCRIPTION, PARENT_DEPARTMENTKEY) values (2, 'XZB', '行政部', '行政部是支撑部门', null);
insert into DEPARTMENT (ID, DEPARTMENT_KEY, DEPARTMENT_VALUE, DESCRIPTION, PARENT_DEPARTMENTKEY) values (3, 'SCB', '市场部', '市场部是公司最大的部门', null);
insert into DEPARTMENT (ID, DEPARTMENT_KEY, DEPARTMENT_VALUE, DESCRIPTION, PARENT_DEPARTMENTKEY) values (4, 'RJB', '软件部', '软件部是研发部的子部门', 'YFB');
insert into DEPARTMENT (ID, DEPARTMENT_KEY, DEPARTMENT_VALUE, DESCRIPTION, PARENT_DEPARTMENTKEY) values (5, 'YJB', '硬件部', '硬件部是研发部的子部门', 'YFB');
CREATE TABLE DICT ( ID NUMBER(19) NOT NULL, DICT_KEY VARCHAR2(20) NOT NULL, DICT_VALUE VARCHAR2(40) NOT NULL, PARENT_DICTKEY VARCHAR2(20), SEQUENCE NUMBER(19), PRIMARY KEY (ID), CONSTRAINT UK_3QSLASHSO6JREMLWNEGXAAQNG UNIQUE (DICT_KEY) );
insert into DICT (ID, DICT_KEY, DICT_VALUE, PARENT_DICTKEY, SEQUENCE) values (1, 'GCS', '工程师', null, null);
insert into DICT (ID, DICT_KEY, DICT_VALUE, PARENT_DICTKEY, SEQUENCE) values (2, 'YJGCS', '硬件工程师', 'GCS', 1);
insert into DICT (ID, DICT_KEY, DICT_VALUE, PARENT_DICTKEY, SEQUENCE) values (3, 'RJGCS', '软件工程师', 'GCS', 2);
CREATE TABLE INFORMATION ( ID NUMBER(19) NOT NULL, AUTHOR VARCHAR2(40), CONTENT VARCHAR2(4000), REFRESH_TIME DATE, TITLE VARCHAR2(100) NOT NULL, PRIMARY KEY (ID) );
CREATE TABLE MAIL ( ID NUMBER(19) NOT NULL, MESSAGE LONG, RECIPIENT VARCHAR2(1000), SENDER VARCHAR2(30), SUBJECT VARCHAR2(200), PRIMARY KEY (ID) );
CREATE TABLE ROLE_AUTHORITY ( ID NUMBER(19) NOT NULL, MENU_CODE VARCHAR2(50) NOT NULL, ROLE_KEY VARCHAR2(40) NOT NULL, PRIMARY KEY (ID) );
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (40, 'department', 'ROLE_USER');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (41, 'information', 'ROLE_USER');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (42, 'typography', 'ROLE_USER');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (43, 'uielements', 'ROLE_USER');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (44, 'buttonsicon', 'ROLE_USER');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (45, 'contentslider', 'ROLE_USER');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (46, 'nestablelist', 'ROLE_USER');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (47, 'jquerydatatables', 'ROLE_USER');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (83, 'sysuser', 'ROLE_RESTRICTED_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (84, 'dict', 'ROLE_RESTRICTED_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (85, 'role', 'ROLE_RESTRICTED_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (86, 'mail', 'ROLE_RESTRICTED_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (87, 'information', 'ROLE_RESTRICTED_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (88, 'typography', 'ROLE_RESTRICTED_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (89, 'buttonsicon', 'ROLE_RESTRICTED_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (90, 'contentslider', 'ROLE_RESTRICTED_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (144, 'charts', 'ROLE_VIP');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (145, 'sysuser', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (146, 'department', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (147, 'dict', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (148, 'role', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (149, 'authority', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (150, 'mail', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (151, 'information', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (152, 'typography', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (153, 'uielements', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (154, 'buttonsicon', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (155, 'contentslider', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (156, 'nestablelist', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (157, 'jquerydatatables', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (158, 'formelements', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (159, 'formelements2', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (160, 'wizardvalidation', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (161, 'uiwidgets', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (162, 'calendar', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (163, 'gallery', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (164, 'pricingtables', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (165, 'invoice', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (166, 'timeline', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (167, 'faq', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (168, 'error404', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (169, 'error500', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (170, 'grid', 'ROLE_ADMIN');
insert into ROLE_AUTHORITY (ID, MENU_CODE, ROLE_KEY) values (171, 'charts', 'ROLE_ADMIN');
CREATE TABLE ROLE ( ID NUMBER(19) NOT NULL, DESCRIPTION VARCHAR2(200), ROLE_KEY VARCHAR2(40) NOT NULL, ROLE_VALUE VARCHAR2(40) NOT NULL, PRIMARY KEY (ID), CONSTRAINT UK_KQ6633UPJKS80IGXJ3RX1F93Q UNIQUE (ROLE_KEY) );
insert into ROLE (ID, DESCRIPTION, ROLE_KEY, ROLE_VALUE) values (1, '这是超级管理员', 'ROLE_ADMIN', '超级管理员');
insert into ROLE (ID, DESCRIPTION, ROLE_KEY, ROLE_VALUE) values (2, null, 'ROLE_RESTRICTED_ADMIN', '普通管理员');
insert into ROLE (ID, DESCRIPTION, ROLE_KEY, ROLE_VALUE) values (3, null, 'ROLE_USER', '普通用户');
insert into ROLE (ID, DESCRIPTION, ROLE_KEY, ROLE_VALUE) values (4, null, 'ROLE_VIP', 'VIP用户');
CREATE TABLE ROLE_PERMISSION ( ROLE_ID NUMBER(19) NOT NULL, PERMISSIONS VARCHAR2(255) );
insert into ROLE_PERMISSION (ROLE_ID, PERMISSIONS) values (1, 'ROLE_ADMIN:*');
insert into ROLE_PERMISSION (ROLE_ID, PERMISSIONS) values (2, 'ROLE_RESTRICTED_ADMIN:*');
insert into ROLE_PERMISSION (ROLE_ID, PERMISSIONS) values (3, 'ROLE_USER:*');
insert into ROLE_PERMISSION (ROLE_ID, PERMISSIONS) values (4, 'ROLE_VIP:*');
ALTER TABLE ROLE_PERMISSION ADD CONSTRAINT FK_J89G87BVIH4D6JBXJCSSRYBKS FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID);
CREATE TABLE SYS_USER ( ID NUMBER(19) NOT NULL, USER_NAME VARCHAR2(40) NOT NULL, SEX NUMBER(1), EMAIL VARCHAR2(30) NOT NULL, PHONE VARCHAR2(20), BIRTHDAY DATE, DEPARTMENT_KEY VARCHAR2(20), PASSWORD VARCHAR2(100) NOT NULL, STATUS NUMBER(1) NOT NULL, LAST_LOGINTIME TIMESTAMP(6), PRIMARY KEY (ID) );
insert into SYS_USER (ID, USER_NAME, SEX, EMAIL, PHONE, BIRTHDAY, DEPARTMENT_KEY, PASSWORD, STATUS, LAST_LOGINTIME) values (1, '杨添', 1, '3228979148@qq.com', '123456789', TIMESTAMP '2015-03-11 00:00:00', 'YFB', '45a1096908da54701e54da1214b4bed426bcd290a443858ac6289bf5f911e37f', 0, TIMESTAMP '2015-07-26 17:24:40');
CREATE TABLE SYSUSER_ROLE ( SYSUSER_ID NUMBER(19) NOT NULL, ROLE_ID NUMBER(19) NOT NULL, PRIMARY KEY (SYSUSER_ID, ROLE_ID) );
insert into SYSUSER_ROLE (SYSUSER_ID, ROLE_ID) values (1, 1);
ALTER TABLE SYSUSER_ROLE ADD CONSTRAINT FK_O4Y1JOE19RWY6XVJIECGLWVSW FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID);
ALTER TABLE SYSUSER_ROLE ADD CONSTRAINT FK_NV0YLO0NRDS5GYR39GAMS7K6Q FOREIGN KEY (SYSUSER_ID) REFERENCES SYS_USER (ID);